### ISSUE TITLE
Erroring out when trying to deploy through heroku

### ISSUE THREAD

**Issue by neemanthnub** [vinayak-7-0-3/Tidal-DL-Telegram#1]
Title
How to reproduce
1. Click on the deploy to heroku
2. Gives an error saying "The content of app.json is not valid; please see [app.json Schema](https://devcenter.heroku.com/articles/app-json-schema) for more information."
The file does not contain a valid JSON entity.

Here's a screenshot
![chrome_ohgl3bqgAF](https://user-images.githubusercontent.com/92370174/156698505-b0b967b5-cf1f-486d-8eff-20f0d0bb7dcd.png)

**Comment by vinayak-7-0-3** [comment]
Fixed
