### ISSUE TITLE
what to do

### ISSUE THREAD

**Issue by rahulbanwasi** [vinayak-7-0-3/Tidal-DL-Telegram#22]
bot - WARNING - 'NoneType' object has no attribute 'id'

**Comment by Omar509666** [comment]
bot - WARNING - 'NoneType' object has no attribute 'id'

**Comment by Omar509666** [comment]
bot - WARNING - 'NoneType' object has no attribute 'id'

**Comment by rahulbanwasi** [comment]
any update so far?

**Comment by rahulbanwasi** [comment]
any update ? (2)

**Comment by vinayak-7-0-3** [comment]
> bot - WARNING - 'NoneType' object has no attribute 'id'

Can you provide the link which caused this error
