### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arjung24** [vinayak-7-0-3/Tidal-DL-Telegram#6]
[tidaltulu-logs-1655019614358.txt](https://github.com/vinayak-7-0-3/Tidal-DL-Telegram/files/8885421/tidaltulu-logs-1655019614358.txt)

Help brother

**Comment by arjung24** [comment]
[tidaltulu-logs-1655020754378.txt](https://github.com/vinayak-7-0-3/Tidal-DL-Telegram/files/8885446/tidaltulu-logs-1655020754378.txt)

**Comment by arjung24** [comment]
Also your session string generator is not working

**Comment by vinayak-7-0-3** [comment]
> Also your session string generator is not working

Its working now.
Error was from Replit side.

**Comment by sayeed205** [comment]
> [tidaltulu-logs-1655019614358.txt](https://github.com/vinayak-7-0-3/Tidal-DL-Telegram/files/8885421/tidaltulu-logs-1655019614358.txt)
> 
> Help brother

Will be fixed soon
